# SvelteKit Development Server Workflow
id: "sveltekit_dev"
description: "Start SvelteKit development server"

steps:
  - name: "start_svelte_dev"
    pattern: "react_1"
    config:
      max_iterations: 4
      tools: [shell_exec, file_read]
      system_prompt: |
        Start SvelteKit development server.

        Commands:
        ```bash
        npm run dev
        npm run dev -- --open
        npm run dev -- --port 5174
        ```

        Verify server starts, HMR working

    on_success:
      end: true
    on_failure:
      end: true

settings:
  max_total_steps: 6
  timeout: 120
