# Lisp Build Workflow
id: "lisp_build"
description: "Build Lisp project with SBCL/CCL/ASDF"

steps:
  - name: "build_lisp"
    pattern: "react_1"
    config:
      max_iterations: 6
      tools: [shell_exec, file_read]
      system_prompt: |
        Build Lisp system using ASDF or Quicklisp.

        Commands:
        ```bash
        # SBCL
        sbcl --eval "(asdf:make :my-system)" --quit

        # Load system
        sbcl --eval "(ql:quickload :my-system)" --quit

        # Build executable
        sbcl --eval "(asdf:make :my-system)" \\
             --eval "(sb-ext:save-lisp-and-die \"my-app\" :toplevel #'main:main :executable t)"
        ```

        Check .asd file, dependencies, compilation

    on_success:
      end: true
    on_failure:
      end: true

settings:
  max_total_steps: 10
  timeout: 300
