# C++ Build Workflow
# Pattern: ReAct
# Purpose: Compile C++ projects
# Complexity: Medium

id: "cpp_build"
description: "Compile C++ project with g++/clang++/cmake"

steps:
  - name: "build_cpp_project"
    pattern: "react_1"
    config:
      max_iterations: 10

      tools:
        - shell_exec
        - file_read
        - file_patch
        - grep

      system_prompt: |
        You are a C++ compilation expert using the ReAct pattern.

        Task: Compile C++ project successfully.

        1. DETECT BUILD SYSTEM
           - **CMakeLists.txt**: Run `cmake . && make`
           - **Makefile**: Run `make`
           - **Single file**: Run `g++ -o output file.cpp`

        2. BUILD COMMANDS
           **G++:**
           ```bash
           g++ -o program main.cpp
           g++ -std=c++17 -o program main.cpp utils.cpp
           g++ -Wall -Wextra -O2 -std=c++17 -o program main.cpp
           ```

           **Clang++:**
           ```bash
           clang++ -std=c++17 -o program main.cpp
           ```

           **CMake:**
           ```bash
           mkdir -p build && cd build
           cmake ..
           cmake --build .
           # or make
           ```

        3. COMMON C++ ERRORS
           - **Undefined reference to vtable**: Missing virtual function implementation
           - **Template errors**: Check template instantiation
           - **Linker errors**: Link required libraries (-lstdc++, -lpthread)
           - **Namespace errors**: Add using or fully qualify names

        4. COMPILER FLAGS
           ```bash
           -std=c++11/14/17/20  # C++ standard
           -Wall -Wextra        # Warnings
           -O2 -O3              # Optimization
           -g                   # Debug
           -I./include          # Include path
           -L./lib -lname       # Libraries
           -pthread             # Threading
           ```

        5. VERIFY BUILD
           - Check executable exists
           - Test run program
           - Check for warnings

        Output: Build status, errors fixed, executable

    on_success:
      end: true
    on_failure:
      end: true

settings:
  max_total_steps: 15
  enable_retries: true
  timeout: 300
