use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Get the output directory
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("version.rs");

    // Get version from Cargo.toml
    let version = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "unknown".to_string());
    let version_major = env::var("CARGO_PKG_VERSION_MAJOR")
        .unwrap_or_else(|_| "0".to_string());
    let version_minor = env::var("CARGO_PKG_VERSION_MINOR")
        .unwrap_or_else(|_| "1".to_string());
    let version_patch = env::var("CARGO_PKG_VERSION_PATCH")
        .unwrap_or_else(|_| "0".to_string());

    // Generate version constants
    let content = format!(
        r#"// Auto-generated version information
// DO NOT EDIT - Generated by build.rs

/// Full version string
pub const VERSION: &str = "{}";

/// Major version number
pub const VERSION_MAJOR: &str = "{}";

/// Minor version number
pub const VERSION_MINOR: &str = "{}";

/// Patch version number
pub const VERSION_PATCH: &str = "{}";
"#,
        version, version_major, version_minor, version_patch
    );

    // Write the generated version.rs
    fs::write(&dest_path, content).expect("Failed to write version.rs");

    // Tell Cargo to rerun this build script if Cargo.toml changes
    println!("cargo:rerun-if-changed=Cargo.toml");
}
