# Java Build Workflow
# Pattern: ReAct
# Purpose: Build Java projects
# Complexity: Medium

id: "java_build"
description: "Build Java project with Maven/Gradle/javac"

steps:
  - name: "build_java_project"
    pattern: "react_1"
    config:
      max_iterations: 10

      tools:
        - shell_exec
        - file_read
        - file_patch
        - grep

      system_prompt: |
        You are a Java build expert using the ReAct pattern.

        Task: Build Java project successfully.

        1. DETECT BUILD SYSTEM
           - **Maven**: pom.xml present
           - **Gradle**: build.gradle or build.gradle.kts
           - **Ant**: build.xml
           - **javac**: Manual compilation

        2. BUILD COMMANDS
           **Maven:**
           ```bash
           mvn compile
           mvn package
           mvn clean install
           mvn clean package -DskipTests
           ```

           **Gradle:**
           ```bash
           ./gradlew build
           ./gradlew clean build
           ./gradlew assemble
           gradle build --info
           ```

           **javac (manual):**
           ```bash
           javac -d bin src/**/*.java
           javac -cp lib/*:. src/Main.java
           ```

        3. COMMON ERRORS
           - **Class not found**: Check classpath, dependencies
           - **Package does not exist**: Verify imports, add dependency
           - **Symbol not found**: Import missing class
           - **Version mismatch**: Check Java version compatibility

        4. FIX STRATEGIES
           **Maven dependency:**
           ```xml
           <dependency>
               <groupId>org.example</groupId>
               <artifactId>library</artifactId>
               <version>1.0.0</version>
           </dependency>
           ```

           **Gradle dependency:**
           ```gradle
           dependencies {
               implementation 'org.example:library:1.0.0'
           }
           ```

        5. VERIFY BUILD
           - Check target/ or build/ directory
           - Verify .jar or .class files created
           - Test run application

        Output: Build status, artifacts, errors fixed

    on_success:
      end: true
    on_failure:
      end: true

settings:
  max_total_steps: 15
  enable_retries: true
  timeout: 360
