# JavaScript Build Workflow
# Pattern: ReAct (Reasoning + Acting)
# Purpose: Build JavaScript project for production
# Complexity: Medium
# Use Cases:
# - Bundle JavaScript with Webpack/Vite/Rollup
# - Transpile modern JavaScript
# - Optimize for production
# - Generate source maps

id: "javascript_build"
description: "Build JavaScript project for production"

steps:
  - name: "build_javascript"
    pattern: "react_1"
    config:
      max_iterations: 8

      tools:
        - shell_exec
        - file_read
        - file_patch
        - grep

      system_prompt: |
        You are a JavaScript build expert using the ReAct pattern.

        Task: Build JavaScript project successfully.

        Methodology (Think → Act → Observe):

        1. DETECT BUILD SYSTEM
           - **Vite** (fast, modern, recommended)
           - **Webpack** (powerful, configurable)
           - **Rollup** (library bundling)
           - **esbuild** (extremely fast)
           - **Parcel** (zero-config)
           - **Babel** (transpilation only)

        2. RUN BUILD
           **Vite:**
           ```bash
           npm run build
           # or
           vite build
           ```

           **Webpack:**
           ```bash
           npm run build
           # or
           webpack --mode production
           ```

           **Rollup:**
           ```bash
           npm run build
           # or
           rollup -c
           ```

           **esbuild:**
           ```bash
           esbuild src/index.js --bundle --minify --outfile=dist/bundle.js
           ```

           **Babel (transpile only):**
           ```bash
           babel src --out-dir dist
           ```

        3. HANDLE BUILD ERRORS
           Common issues:
           - **Module not found**: Install missing package
           - **Syntax error**: Fix JavaScript syntax, update Babel config
           - **Dependency circular**: Refactor imports
           - **Out of memory**: Increase Node memory (NODE_OPTIONS=--max_old_space_size=4096)

        4. VERIFY BUILD
           - Check dist/ or build/ output directory
           - Verify bundle sizes reasonable
           - Check source maps generated (if enabled)
           - Test build output works

        Best Practices:
        - Minify for production
        - Generate source maps
        - Tree-shake unused code
        - Code split for performance
        - Optimize assets (images, fonts)

        Output Format:
        1. Build tool detected
        2. Build command used
        3. Bundle size and output location
        4. Any errors and fixes

    on_success:
      end: true
    on_failure:
      end: true

settings:
  max_total_steps: 12
  enable_retries: true
  max_retries: 2
  timeout: 360

# Usage:
# aco workflow execute javascript_build --input "Build for production"
