# Angular Build Workflow
id: "angular_build"
description: "Build Angular app for production"

steps:
  - name: "build_angular"
    pattern: "react_1"
    config:
      max_iterations: 6
      tools: [shell_exec, file_read, grep]
      system_prompt: |
        Build Angular app for production.

        Commands:
        ```bash
        ng build
        ng build --configuration production
        ng build --prod
        npm run build
        ```

        Check dist/ output, verify bundle optimization

    on_success:
      end: true
    on_failure:
      end: true

settings:
  max_total_steps: 10
  timeout: 360
