# Angular Development Server Workflow
id: "angular_dev"
description: "Start Angular development server"

steps:
  - name: "start_ng_serve"
    pattern: "react_1"
    config:
      max_iterations: 4
      tools: [shell_exec, file_read]
      system_prompt: |
        Start Angular development server.

        Commands:
        ```bash
        ng serve
        ng serve --port 4201
        ng serve --open
        npm start
        ```

        Verify server starts on http://localhost:4200

    on_success:
      end: true
    on_failure:
      end: true

settings:
  max_total_steps: 6
  timeout: 120
