//! TOML configuration file generation
//!
//! Generates TOML configuration files from YAML install configs.

use crate::schema::{AcoTomlConfig, OrcaTomlConfig};
use anyhow::Result;
use std::path::Path;
use tracing::{debug, info, warn};

/// Configuration file generator
pub struct ConfigGenerator {
    force: bool,
}

impl ConfigGenerator {
    pub fn new(force: bool) -> Self {
        Self { force }
    }

    /// Generate orca TOML config file
    pub fn generate_orca_toml(&self, path: &Path, config: &OrcaTomlConfig) -> Result<()> {
        info!("Generating orca TOML config at {:?}", path);

        // Ensure parent directory exists
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        // Check if file exists
        if path.exists() && !self.force {
            warn!(
                "Orca config already exists at {:?}, skipping (use --force to overwrite)",
                path
            );
            return Ok(());
        }

        // Generate TOML content
        let toml_content = self.generate_orca_toml_content(config)?;

        // Write file
        std::fs::write(path, toml_content)?;
        debug!("Wrote orca TOML config");

        Ok(())
    }

    /// Generate aco TOML config file
    pub fn generate_aco_toml(&self, path: &Path, config: &AcoTomlConfig) -> Result<()> {
        info!("Generating aco TOML config at {:?}", path);

        // Ensure parent directory exists
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        // Check if file exists
        if path.exists() && !self.force {
            warn!(
                "ACO config already exists at {:?}, skipping (use --force to overwrite)",
                path
            );
            return Ok(());
        }

        // Generate TOML content
        let toml_content = self.generate_aco_toml_content(config)?;

        // Write file
        std::fs::write(path, toml_content)?;
        debug!("Wrote aco TOML config");

        Ok(())
    }

    fn generate_orca_toml_content(&self, config: &OrcaTomlConfig) -> Result<String> {
        let mut content = String::new();

        // Header comment
        content.push_str("# Orca Configuration\n");
        content.push_str("# Generated by orca_install\n\n");

        // Database section
        content.push_str("[database]\n");
        content.push_str(&format!("path = \"{}\"\n", config.database.path));
        content.push('\n');

        // LLM section
        content.push_str("[llm]\n");
        content.push_str(&format!("provider = \"{}\"\n", config.llm.provider));
        content.push_str(&format!("model = \"{}\"\n", config.llm.model));
        if let Some(ref api_key) = config.llm.api_key {
            content.push_str(&format!("api_key = \"{}\"\n", api_key));
        }
        if let Some(ref api_base) = config.llm.api_base {
            content.push_str(&format!("api_base = \"{}\"\n", api_base));
        }
        content.push_str(&format!("temperature = {}\n", config.llm.temperature));
        content.push_str(&format!("max_tokens = {}\n", config.llm.max_tokens));
        content.push('\n');

        // Execution section
        content.push_str("[execution]\n");
        content.push_str(&format!(
            "max_concurrent_tasks = {}\n",
            config.execution.max_concurrent_tasks
        ));
        content.push_str(&format!("task_timeout = {}\n", config.execution.task_timeout));
        content.push_str(&format!("streaming = {}\n", config.execution.streaming));
        content.push_str(&format!(
            "max_iterations = {}\n",
            config.execution.max_iterations
        ));
        content.push_str(&format!(
            "default_pattern = \"{}\"\n",
            config.execution.default_pattern
        ));
        content.push_str(&format!(
            "show_thinking = {}\n",
            config.execution.show_thinking
        ));
        content.push('\n');

        // Logging section
        content.push_str("[logging]\n");
        content.push_str(&format!("level = \"{}\"\n", config.logging.level));
        content.push_str(&format!("format = \"{}\"\n", config.logging.format));
        content.push_str(&format!("colored = {}\n", config.logging.colored));
        content.push_str(&format!("timestamps = {}\n", config.logging.timestamps));
        if let Some(ref log_dir) = config.logging.log_directory {
            content.push_str(&format!("log_directory = \"{}\"\n", log_dir));
        }
        content.push_str(&format!("log_prefix = \"{}\"\n", config.logging.log_prefix));
        content.push('\n');

        // Budget section
        content.push_str("[budget]\n");
        if let Some(ref default_budget) = config.budget.default_budget {
            content.push_str(&format!("default_budget = \"{}\"\n", default_budget));
        }
        content.push_str(&format!(
            "enforce_budgets = {}\n",
            config.budget.enforce_budgets
        ));
        content.push_str(&format!("log_usage = {}\n", config.budget.log_usage));
        content.push_str(&format!(
            "alert_threshold = {}\n",
            config.budget.alert_threshold
        ));
        content.push('\n');

        // Workflow section
        content.push_str("[workflow]\n");
        if let Some(ref profile) = config.workflow.default_llm_profile {
            content.push_str(&format!("default_llm_profile = \"{}\"\n", profile));
        }
        if let Some(ref planner) = config.workflow.default_planner_llm {
            content.push_str(&format!("default_planner_llm = \"{}\"\n", planner));
        }
        if let Some(ref worker) = config.workflow.default_worker_llm {
            content.push_str(&format!("default_worker_llm = \"{}\"\n", worker));
        }
        content.push_str(&format!(
            "enable_caching = {}\n",
            config.workflow.enable_caching
        ));
        content.push_str(&format!(
            "cache_ttl_secs = {}\n",
            config.workflow.cache_ttl_secs
        ));
        content.push_str(&format!(
            "max_duration_secs = {}\n",
            config.workflow.max_duration_secs
        ));
        content.push('\n');

        // Backup section (optional)
        if let Some(ref backup) = config.backup {
            content.push_str("[backup]\n");
            if let Some(ref dir) = backup.backup_dir {
                content.push_str(&format!("backup_dir = \"{}\"\n", dir));
            }
            content.push('\n');
        }

        Ok(content)
    }

    fn generate_aco_toml_content(&self, config: &AcoTomlConfig) -> Result<String> {
        let mut content = String::new();

        // Header comment
        content.push_str("# ACO Configuration\n");
        content.push_str("# Generated by orca_install\n\n");

        // Server section
        content.push_str("[server]\n");
        content.push_str(&format!("host = \"{}\"\n", config.server.host));
        content.push_str(&format!("port = {}\n", config.server.port));
        content.push_str(&format!("ws_path = \"{}\"\n", config.server.ws_path));
        content.push_str(&format!("enable_tls = {}\n", config.server.enable_tls));
        content.push('\n');

        // Client section
        content.push_str("[client]\n");
        content.push_str(&format!(
            "orchestrator_url = \"{}\"\n",
            config.client.orchestrator_url
        ));
        content.push_str(&format!("auto_connect = {}\n", config.client.auto_connect));
        content.push_str(&format!(
            "session_timeout = {}\n",
            config.client.session_timeout
        ));
        content.push_str(&format!(
            "reconnect_attempts = {}\n",
            config.client.reconnect_attempts
        ));
        content.push_str(&format!(
            "reconnect_delay_ms = {}\n",
            config.client.reconnect_delay_ms
        ));
        content.push('\n');

        // Tools section
        content.push_str("[tools]\n");
        if config.tools.enabled_tools.is_empty() {
            content.push_str("enabled_tools = []\n");
        } else {
            let tools_str: Vec<String> = config
                .tools
                .enabled_tools
                .iter()
                .map(|t| format!("\"{}\"", t))
                .collect();
            content.push_str(&format!("enabled_tools = [{}]\n", tools_str.join(", ")));
        }
        content.push_str(&format!(
            "execution_timeout = {}\n",
            config.tools.execution_timeout
        ));
        content.push('\n');

        // UI section
        content.push_str("[ui]\n");
        content.push_str(&format!("enable_tui = {}\n", config.ui.enable_tui));
        content.push_str(&format!("log_level = \"{}\"\n", config.ui.log_level));
        content.push_str(&format!("colored_output = {}\n", config.ui.colored_output));
        content.push_str(&format!("show_timestamps = {}\n", config.ui.show_timestamps));
        content.push_str(&format!("show_thinking = {}\n", config.ui.show_thinking));
        content.push('\n');

        Ok(content)
    }
}
