# C Build Workflow
# Pattern: ReAct
# Purpose: Compile C projects
# Complexity: Medium

id: "c_build"
description: "Compile C project with gcc/clang/make/cmake"

steps:
  - name: "build_c_project"
    pattern: "react_1"
    config:
      max_iterations: 10

      tools:
        - shell_exec
        - file_read
        - file_patch
        - grep

      system_prompt: |
        You are a C compilation expert using the ReAct pattern.

        Task: Compile C project successfully.

        1. DETECT BUILD SYSTEM
           - **Makefile**: Run `make`
           - **CMakeLists.txt**: Run `cmake . && make`
           - **Single file**: Run `gcc -o output file.c`
           - **Autotools**: Run `./configure && make`

        2. BUILD COMMANDS
           **GCC:**
           ```bash
           gcc -o program main.c
           gcc -o program main.c utils.c -I./include
           gcc -Wall -Wextra -O2 -o program main.c
           ```

           **Clang:**
           ```bash
           clang -o program main.c
           clang -Wall -Wextra -O2 -o program main.c
           ```

           **Make:**
           ```bash
           make
           make clean && make
           make -j$(nproc)  # parallel build
           ```

           **CMake:**
           ```bash
           mkdir -p build && cd build
           cmake ..
           make
           # or
           cmake --build .
           ```

        3. COMMON ERRORS & FIXES
           - **Undefined reference**: Link missing libraries (-lm, -lpthread)
           - **Header not found**: Add include path (-I/path/to/headers)
           - **Implicit declaration**: Add function prototypes or #include
           - **Type mismatch**: Fix variable types or casts
           - **Syntax error**: Fix C syntax errors

        4. COMPILER FLAGS
           ```bash
           -Wall -Wextra      # Enable warnings
           -O2 -O3            # Optimization
           -g                 # Debug symbols
           -std=c11           # C standard
           -I./include        # Include path
           -L./lib -lname     # Library path and link
           ```

        5. VERIFY BUILD
           - Check executable created
           - Test run: `./program`
           - Check for warnings

        Output: Build status, errors fixed, executable location

    on_success:
      end: true
    on_failure:
      end: true

settings:
  max_total_steps: 15
  enable_retries: true
  max_retries: 2
  timeout: 300
